// Database types (will be generated by Supabase CLI)
export interface Profile {
  id: string;
  user_id: string;
  nome: string | null;
  email: string | null;
  tema: 'light' | 'dark' | 'system';
  moeda: 'BRL' | 'USD' | 'EUR';
  formato_data: 'DD/MM/YYYY' | 'MM/DD/YYYY' | 'YYYY-MM-DD';
  created_at: string;
}

export interface Empresa {
  id: string;
  user_id: string;
  nome: string;
  descricao: string | null;
  ativa: boolean;
  created_at: string;
}

export interface Categoria {
  id: string;
  user_id: string;
  nome: string;
  tipo: 'entrada' | 'saida' | 'ambos';
  cor: string;
  created_at: string;
}

export interface Transacao {
  id: string;
  user_id: string;
  data: string;
  hora: string | null;
  valor: number;
  origem_id: string;
  destino_id: string;
  categoria_id: string | null;
  descricao: string | null;
  agendado: boolean;
  data_agendamento: string | null;
  created_at: string;
  updated_at: string;
  // Joined fields
  origem?: Empresa;
  destino?: Empresa;
  categoria?: Categoria;
}

export interface Tarefa {
  id: string;
  user_id: string;
  titulo: string;
  descricao: string | null;
  data: string | null;
  hora: string | null;
  concluida: boolean;
  created_at: string;
  updated_at: string;
}

export interface Saldo {
  origem_id: string;
  origem_nome: string;
  destino_id: string;
  destino_nome: string;
  saldo: number;
}

// Form types
export interface TransacaoFormData {
  data: string;
  hora?: string;
  valor: number;
  origem_id: string;
  destino_id: string;
  categoria_id?: string;
  descricao?: string;
  agendado: boolean;
  data_agendamento?: string;
}

export interface EmpresaFormData {
  nome: string;
  descricao?: string;
}

export interface CategoriaFormData {
  nome: string;
  tipo: 'entrada' | 'saida' | 'ambos';
  cor: string;
}

export interface TarefaFormData {
  titulo: string;
  descricao?: string;
  data?: string;
  hora?: string;
}
